#!/usr/bin/env python3
"""extract_runtime_contexts.py — emit pipeline-runtime YAML files from
workflow/contexts/<ctx>.yaml on the bridge side.

The bridge stores ONE yaml per context (workflow/contexts/<ctx>.yaml) carrying
all surfaces — /debrief routing, roster, entities, AND the transcription
pipeline runtime config in `integrations.transcription`. The worker host runs
a bash script (transcribe-worker.sh) that parses flat top-level keys via awk —
much simpler than a real YAML parser. This script bridges the two: it reads
each bridge context, extracts `integrations.transcription`, and writes a flat
<ctx>.yaml that the worker can read (language, library, output, notify, plus
optional tracks_default and mic_speaker).

Discovery rule (codified):
    For every workflow/contexts/*.yaml:
      if integrations.transcription is present:
        this is a transcription context;
        emit <out_dir>/<id>.yaml with its fields flattened.

Run from the bridge repo root before rsyncing to the worker. The worker host
comes from $TRANSCRIBE_WORKER (or your bridge-config's worker.host) — there is
no default host; the `:?` expansion below fails loud when it is unset:

    python3 skills/meeting-transcription/scripts/extract_runtime_contexts.py \\
        --src workflow/contexts \\
        --out /tmp/runtime-contexts
    rsync -av --delete /tmp/runtime-contexts/ \\
        "${TRANSCRIBE_WORKER:?set TRANSCRIBE_WORKER to the worker host}":transcribe-pipeline/contexts/

The `--delete` matters: it cleans up obsolete runtime yamls (e.g.
customer-x.yaml.bak) on the worker so we don't carry around stale config.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml


def extract(src_dir: Path, out_dir: Path) -> int:
    if not src_dir.is_dir():
        print(f"FATAL: src_dir {src_dir} not a directory", file=sys.stderr)
        return 2
    out_dir.mkdir(parents=True, exist_ok=True)

    emitted = 0
    skipped = []
    for src in sorted(src_dir.glob("*.yaml")):
        if src.name.startswith("_"):
            continue
        try:
            data = yaml.safe_load(src.read_text())
        except yaml.YAMLError as exc:
            print(f"WARN  {src.name}: invalid YAML ({exc})", file=sys.stderr)
            continue
        if not isinstance(data, dict):
            continue
        block = (data.get("integrations") or {}).get("transcription")
        if not block:
            skipped.append(src.stem)
            continue

        ctx = data.get("id") or src.stem
        if not isinstance(ctx, str) or not ctx:
            print(f"WARN  {src.name}: missing/invalid `id` — skipping", file=sys.stderr)
            continue

        # Required fields — schema enforces presence, but be defensive on
        # ad-hoc edits that bypass validation.
        for required in ("language", "library", "output"):
            if required not in block:
                print(f"WARN  {src.name}: integrations.transcription missing `{required}` — skipping",
                      file=sys.stderr)
                break
        else:
            flat = {
                "language": block["language"],
                "library":  block["library"],
                "output":   block["output"],
                "notify":   bool(block.get("notify", True)),
            }
            if "tracks_default" in block:
                flat["tracks_default"] = block["tracks_default"]
            if "mic_speaker" in block:
                flat["mic_speaker"] = block["mic_speaker"]

            target = out_dir / f"{ctx}.yaml"
            header = (
                f"# Generated by extract_runtime_contexts.py — DO NOT EDIT.\n"
                f"# Source: workflow/contexts/{src.name}\n"
                f"# Edit the source on the bridge side; redeploy to update.\n"
            )
            target.write_text(header + yaml.safe_dump(flat, sort_keys=False))
            print(f"emit  {ctx} → {target}")
            emitted += 1

    if skipped:
        print(f"skip  no integrations.transcription: {', '.join(skipped)}")
    print(f"done  {emitted} context(s) emitted into {out_dir}")
    return 0 if emitted else 1


def main() -> int:
    ap = argparse.ArgumentParser(
        description=(__doc__ or "").splitlines()[0] if __doc__ else None
    )
    ap.add_argument("--src", default="workflow/contexts",
                    help="bridge contexts directory (default: workflow/contexts)")
    ap.add_argument("--out", default="/tmp/runtime-contexts",
                    help="output directory for flat runtime yamls (default: /tmp/runtime-contexts)")
    args = ap.parse_args()
    return extract(Path(args.src).resolve(), Path(args.out).resolve())


if __name__ == "__main__":
    sys.exit(main())
